@startuml
'https://plantuml.com/use-case-diagram

actor Cliente
actor Restaurante
rectangle {
Cliente -- (Mostrar menú)
Cliente -- (Pedir comida)
(Mostrar menú) -- Restaurante
}
(Entregar comida) -- Restaurante

@enduml
